// All site content lives here — edit this file to update the portfolio.

export const profile = {
  name: 'Rupan Chakkaravarthy E',
  callsign: 'RUPAN C.E',
  role: 'Technical Lead — Solutions',
  tagline: 'From cockpits to agents.',
  summary:
    'Ten years building systems where failure is visible immediately — fighter-jet simulators, ARINC 661 cockpit displays, XR hardware integration. Now applying that same discipline to AI: multi-agent orchestration platforms that take software from spec to merged, tested code with humans on the approval gates.',
  location: 'Bangalore, India',
  email: 'erupanc@gmail.com',
  phone: '+91 8807626297',
  github: 'https://github.com/RupanRC',
  company: 'MicroGenesis TechSoft Pvt Ltd',
}

export const stats = [
  { value: '10', unit: 'YRS', label: 'ENGINEERING' },
  { value: '20+', unit: 'SYSTEMS', label: 'DELIVERED · DEFENSE TO AI' },
  { value: '8', unit: 'AGENTS', label: 'ORCHESTRATED IN PARALLEL' },
  { value: '5', unit: 'DOMAINS', label: 'DEFENSE · XR · AI · GIS · WEB' },
  { value: '9+', unit: 'DEVICES', label: 'XR HARDWARE INTEGRATED' },
]

export const timeline = [
  { year: '2016', phase: 'GAME & VR DEV', note: 'Unity, networked gameplay, first VR builds for Rift, Vive and Windows MR.' },
  { year: '2018', phase: 'XR ENGINEER', note: 'AR/VR products and prototypes at D2VR — interactions, SLAM, museum installations.' },
  { year: '2019', phase: 'FIGHTER-JET SIMULATOR', note: 'Deployed at a national aeronautics R&D agency. VR simulator for an indigenous fighter — HUD shaders, cockpit physics, hand tracking. Team lead.' },
  { year: '2021', phase: 'AVIONICS DISPLAYS', note: 'ARINC 661 cockpit display systems in C and OpenGL for indigenous fighter programs. Low-latency symbology, multi-partition displays.' },
  { year: '2024', phase: 'PROJECT MANAGER', note: 'MicroGenesis TechSoft. Technical manager across GIS, robotics and real-time programs at national defense R&D labs.' },
  { year: '2025', phase: 'AI PLATFORM ARCHITECT', note: 'Designing and shipping agentic AI systems — an AI-SDLC orchestration platform, RAG pipelines for flight telemetry, AR inspection products.' },
]

export const doctrine = [
  {
    id: 'SPEC',
    title: 'Spec before code',
    body: 'Every feature starts as a written spec with numbered acceptance criteria and passes through approval gates. Aviation taught me that checklists are not bureaucracy — they are how complex systems stay survivable.',
  },
  {
    id: 'TDD',
    title: 'Tests are the contract',
    body: 'TDD by default — EditMode suites in Unity, E2E in the browser, regression packs on platforms. Work is done when the suite is green, not when it looks done.',
  },
  {
    id: 'HW',
    title: 'Verify on real hardware',
    body: 'A feature verified on a physical headset, tablet or deployed portal is worth ten verified on a dev machine. I close the loop on the device the user actually holds.',
  },
  {
    id: 'AUTO',
    title: 'Automate the meta-work',
    body: 'Weekly reports, cost workbooks, pitch decks, WBS documents — all generated by tooling I built once. Human hours go to decisions, not formatting.',
  },
  {
    id: 'GATE',
    title: 'Autonomy with human gates',
    body: 'I run fleets of AI agents, but every merge crosses a human approval gate with a tamper-proof audit trail. Trust the machine to work; verify before it lands.',
  },
  {
    id: 'SHIP',
    title: 'Ship in small, verified steps',
    body: 'Features land as small increments behind gates, each verified before the next begins. Pace comes from the system — automation, tests and tooling — never from heroics.',
  },
]

export const projects = [
  {
    tag: 'AI-SDLC',
    accent: 'amber',
    name: 'FORGE — AI Software Delivery Platform',
    period: '2026',
    role: 'Architect & sole builder',
    description:
      'An orchestration platform that drives AI coding agents through a full spec → plan → implement → review → QA pipeline with human approval gates — self-running and self-validating.',
    highlights: [
      'Dependency-wave scheduler running up to 8 Claude agents in isolated git worktrees',
      'Automated browser testing verifies every acceptance criterion — it caught a real data-loss defect, and the system fixed itself',
      'Code-knowledge-graph layer so agents consult a graph instead of re-reading files',
      'Local-model routing (Ollama-class) for fully on-premise deployment',
    ],
    stack: ['TypeScript', 'Node.js', 'Claude Agents', 'SSE', 'Knowledge Graphs', 'Ollama'],
  },
  {
    tag: 'XR · QA',
    accent: 'cyan',
    name: 'Qualia — AR Quality Inspection',
    period: '2026',
    role: 'Product engineer',
    description:
      'Mixed-reality inspection for manufacturing lines: an in-headset HUD walks operators through dynamic checklists, with a management portal for evidence, analytics and rework traceability.',
    highlights: [
      'Unity + MRTK3 headset build and ARCore tablet port at full feature parity — verified on physical hardware',
      'Test-driven from the first commit — EditMode and Play-mode E2E suites',
      'Failure → rework → re-inspection workflow with first-pass-yield and scrap-rate analytics',
      'Real-time sync with reconnect resilience and offline retry queues for factory-floor conditions',
    ],
    stack: ['Unity', 'MRTK3', 'ARCore', 'C#', 'React', 'Express', 'SQLite'],
  },
  {
    tag: 'RAG · DATA',
    accent: 'cyan',
    name: 'Flight Data Insights Platform',
    period: '2025–26',
    role: 'Platform engineer',
    description:
      'A telemetry-analysis portal for flight-test data: RAG-powered querying over raw .dat telemetry, natural-language-to-SQL over live databases, and video evidence pipelines — deployed fully air-gapped.',
    highlights: [
      'NL→SQL (Vanna 2.0) verified live across 13 datasets on the deployed portal',
      'Telemetry ingestion profiling 63-column .dat files with and without parameter headers',
      'MPEG-2 and audio-only video ingest with MP4 playback proxies',
      'Complete offline delivery: Docker images, self-contained installers, air-gap patch bundles',
    ],
    stack: ['Python', 'RAGFlow', 'Vanna 2.0', 'Ollama', 'React', 'Docker', 'MSSQL'],
  },
  {
    tag: 'DEFENSE · SIM',
    accent: 'amber',
    name: 'XR Fighter-Jet Simulator',
    period: '2019–21',
    role: 'Team lead',
    description:
      'Indigenous VR fighter-jet simulator built for a national aeronautics agency: full cockpit interaction, HUD symbology, environment simulation and hand tracking.',
    highlights: [
      'Custom world-space-UV shaders for HUD simulation; physics-joint cockpit switches',
      'Editor scripting auto-rigged hundreds of cockpit controls from engineering spreadsheets',
      'Leap Motion hand-tracked interaction and 6-DOF Quest visualization',
      'Symbology drawing scheduled across multiple cockpit display surfaces',
    ],
    stack: ['Unity', 'C#', 'HLSL', 'Leap Motion', 'Varjo', 'Oculus'],
  },
  {
    tag: 'AVIONICS',
    accent: 'amber',
    name: 'Cockpit Display System (ARINC 661)',
    period: '2021–23',
    role: 'Team lead',
    description:
      'Certified-standard cockpit display software for indigenous fighter programs — low-latency rendering of SVG-based display pages in C and OpenGL.',
    highlights: [
      'ARINC 661-compliant multi-partition dynamic displays with modular updates',
      'Shader-based rendering for real-time graphical elements',
      'Epiphan video capture integration with real-time cropping and UDP streaming via OpenCV',
      'Ada ↔ C++ integration over DLLs and network protocols for airworthy test units',
    ],
    stack: ['C', 'C++', 'OpenGL', 'Ada', 'OpenCV', 'Python'],
  },
  {
    tag: 'DATA · OPS',
    accent: 'cyan',
    name: 'Supplier Intelligence Platform',
    period: '2025–26',
    role: 'Engineer & proposal architect',
    description:
      'A supplier-data aggregation platform with scraping architecture spanning 50+ sources, plus the full commercial package — WBS, staffing plan and costed SOW for a six-month, six-person engagement.',
    highlights: [
      'App-level auth hardening and maintenance-mode infrastructure',
      'Scraping matrix across suppliers and aggregators',
      'Costed delivery plan with market-rate modeling',
    ],
    stack: ['React', 'Vite', 'Node.js', 'Scraping', 'xlsx tooling'],
  },
  {
    tag: 'MARITIME · GIS',
    accent: 'cyan',
    name: 'IMSAS — Indian Maritime Situational Awareness System',
    period: '2021–23',
    role: 'Senior engineer',
    description:
      'GIS-based situational awareness system for maritime operations — a real-time common operating picture built on a distributed event-streaming backbone.',
    highlights: [
      'Qt / C++ GIS front end rendering live tracks and layered maritime data',
      'PostgreSQL-backed data store for tracks, geodata and mission records',
      'Kafka and RabbitMQ event streaming for real-time data distribution across consoles',
    ],
    stack: ['Qt', 'C++', 'PostgreSQL', 'Kafka', 'RabbitMQ', 'GIS'],
  },
  {
    tag: 'ERGONOMICS',
    accent: 'cyan',
    name: 'Real-Time Pilot Ergonomics',
    period: '2024–25',
    role: 'Lead engineer',
    description:
      'Motion-capture-driven ergonomic analysis of pilots under high-load maneuvering — bone-data extraction, stress metrics, session playback and automated PDF reporting.',
    highlights: [
      'Xsens Movella motion-capture suit integration in Unity',
      'Timestamped posture logging with CSV/JSON export for MATLAB analysis',
      'Auto-generated ergonomic score reports',
    ],
    stack: ['Unity', 'C#', 'Xsens', 'Data pipelines'],
  },
  {
    tag: 'SECURITY',
    accent: 'amber',
    name: 'Air-Gap Data Exchange PoC',
    period: '2026',
    role: 'Solution architect',
    description:
      'A complete architecture for moving reviewed data between an offline system and a common server — packaging, auth envelopes, and field-level diff review on both ends — with a working sample application and full documentation.',
    highlights: [
      'ARINC-style change-set packaging with authentication envelopes',
      'File-driven generic UI renderer with editable working copies',
      'Architecture deck, file-format spec and demo script included',
    ],
    stack: ['TypeScript', 'Vite', 'Custom file formats'],
  },
]

// Personal experiments and open tooling — the after-hours hangar.
export const lab = [
  {
    name: 'Plethora',
    desc: 'ADHD-aware daily companion — a proactive coaching agent that keeps every task primed with reward, reason and gentle consequences.',
    stack: 'Next.js 15 · Neon Postgres · LLM tool-calling',
  },
]

// Complete mission index — every system on the record.
export const archive = [
  { name: 'Bomb-Drop Trajectory Simulation', desc: 'Weapon-release trajectory playback in FlightGear and Unity driven by real trajectory data.', tags: 'FlightGear · Unity' },
  { name: 'Fighter-Jet Sensors Simulation', desc: 'Multi-monitor, multi-window sensor simulation with FlightGear and XLIB on Ubuntu.', tags: 'FlightGear · XLIB · Linux' },
  { name: 'Synthetic Terrain', desc: 'Shader development for synthetic terrain generation in FlightGear.', tags: 'GLSL · FlightGear' },
  { name: 'Lane Detection Integration', desc: 'Python computer-vision lane detection wired into FlightGear via C/C++.', tags: 'Python · OpenCV · C++' },
  { name: 'UDP Video Streaming', desc: 'Screen and window capture encoded with OpenCV and streamed over UDP protocols.', tags: 'C++ · OpenCV · UDP' },
  { name: 'Multi-Region Large-Area Display', desc: 'Windows C++ display-wall software with interchangeable touch-driven pages.', tags: 'C++ · Touch UI' },
  { name: 'ECFM LRU', desc: 'Test-case generation and component testing for a real-time airworthy unit; Ada integrated with C++ over DLLs and network protocols.', tags: 'Ada · C++ · Avionics' },
  { name: 'AUV Software (ECA A9)', desc: 'Autonomous underwater vehicle software on the ROS2 / NAV2 stack.', tags: 'ROS2 · NAV2 · Robotics' },
  { name: 'LIDAR Point-Cloud VR', desc: 'Drone-captured LIDAR point clouds brought into real-time VR walkthroughs, with MIT Chennai.', tags: 'Unity · LIDAR · VR' },
  { name: 'Self-Hosted LLM Backend', desc: 'Multimodal LLM management backend plus an open-source chat platform with user and model access control, deployed via Docker.', tags: 'Docker · Ollama · LLM Ops' },
  { name: 'AI Pair-Programming Rollout', desc: 'Open-source AI agent plugins in VS Code wired to local LLMs — code generation, autocomplete and in-IDE chat for the team.', tags: 'VS Code · Local LLMs' },
  { name: 'Self-Hosted Video Conferencing', desc: 'Low-latency Google Meet alternative deployed via Docker for real-time communication.', tags: 'Docker · WebRTC' },
  { name: 'MMORPG PC VR Game', desc: 'Building systems, procedural terrain generation and networking modules for a VR MMORPG, with a Canadian PhD researcher.', tags: 'Unity · Networking' },
  { name: 'Museum Interactives', desc: 'Puli-Meka turn-based multiplayer strategy game with AI for an archaeological museum, a 4-way multi-user touch table, and a VR 360° annotated tour.', tags: 'Unity · Touch · VR' },
  { name: 'AR Sketch (SLAM)', desc: 'AR drawing application anchoring sketches in real-world space with SLAM.', tags: 'ARCore · SLAM' },
]

export const systems = [
  {
    code: 'SYS-01',
    name: 'AI & Agents',
    items: ['Claude / Claude Code orchestration', 'Multi-agent pipelines & MCP', 'RAG — RAGFlow, Chroma', 'NL→SQL — Vanna 2.0', 'Local LLMs — Ollama', 'Code knowledge graphs'],
  },
  {
    code: 'SYS-02',
    name: 'XR & Simulation',
    items: ['Unity 3D · C#', 'MRTK3 · ARCore · ARFoundation', 'OpenVR · SteamVR · Oculus', 'Varjo XR-3/4 · Quest · Vive', 'Leap Motion · Xsens · SenseGlove', 'FlightGear · Unreal'],
  },
  {
    code: 'SYS-03',
    name: 'Real-Time & Avionics',
    items: ['C · C++ · OpenGL', 'ARINC 661 displays', 'Ada embedded integration', 'Qt · ROS2 · NAV2', 'GLSL / HLSL shaders', 'OpenCV · UDP video streaming'],
  },
  {
    code: 'SYS-04',
    name: 'Web & Platform',
    items: ['TypeScript · React · Vite', 'Node.js · Express · SSE', 'FastAPI · Python services', 'Tauri v2 desktop apps', 'SQLite · MySQL · MSSQL', 'Tailwind · design systems', 'Auth — scrypt, HMAC, RBAC'],
  },
  {
    code: 'SYS-05',
    name: 'Ops & Delivery',
    items: ['Docker · nginx · WSL', 'Air-gapped Linux deployment', 'Git worktree orchestration', 'TDD · browser automation', 'WBS / SOW / costing tooling'],
  },
]
