// All site content lives here — edit this file to update the portfolio.

export const profile = {
  name: 'Rupan Chakkaravarthy E',
  callsign: 'RUPAN C.E',
  role: 'Senior Engineer · Project Manager · AI Platform Architect',
  tagline: 'From cockpits to agents.',
  summary:
    'Ten years building systems where failure is visible immediately — fighter-jet simulators, ARINC 661 cockpit displays, XR hardware integration. Now applying that same discipline to AI: multi-agent orchestration platforms that take software from spec to merged, tested code with humans on the approval gates.',
  location: 'Chennai, India',
  email: 'erupanc@gmail.com',
  phone: '+91 8807626297',
  github: 'https://github.com/RupanRC',
  company: 'MicroGenesis TechSoft Pvt Ltd',
}

export const stats = [
  { value: '10', unit: 'YRS', label: 'ENGINEERING' },
  { value: '850', unit: 'TESTS', label: 'GREEN · ONE PLATFORM' },
  { value: '8', unit: 'AGENTS', label: 'ORCHESTRATED IN PARALLEL' },
  { value: '18', unit: 'DAYS', label: 'REPO → SELF-RUNNING PLATFORM' },
  { value: '110+', unit: 'TASKS', label: 'SHIPPED PER WEEK' },
]

export const timeline = [
  { year: '2016', phase: 'GAME & VR DEV', note: 'Unity, networked gameplay, first VR builds for Rift, Vive and Windows MR.' },
  { year: '2018', phase: 'XR ENGINEER', note: 'AR/VR products and prototypes at D2VR — interactions, SLAM, museum installations.' },
  { year: '2019', phase: 'FIGHTER-JET SIMULATOR', note: 'Deployed at a national aeronautics R&D agency. VR simulator for an indigenous fighter — HUD shaders, cockpit physics, hand tracking. Team lead.' },
  { year: '2021', phase: 'AVIONICS DISPLAYS', note: 'ARINC 661 cockpit display systems in C and OpenGL for indigenous fighter programs. Low-latency symbology, multi-partition displays.' },
  { year: '2024', phase: 'PROJECT MANAGER', note: 'MicroGenesis TechSoft. Technical manager across GIS, robotics and real-time programs at national defense R&D labs.' },
  { year: '2025', phase: 'AI PLATFORM ARCHITECT', note: 'Designing and shipping agentic AI systems — an AI-SDLC orchestration platform, RAG pipelines for flight telemetry, AR inspection products. Ten-x personal throughput, verified by tests.' },
]

export const doctrine = [
  {
    id: 'SPEC',
    title: 'Spec before code',
    body: 'Every feature starts as a written spec with numbered acceptance criteria and passes through approval gates. Aviation taught me that checklists are not bureaucracy — they are how complex systems stay survivable.',
  },
  {
    id: 'TDD',
    title: 'Tests are the contract',
    body: 'TDD by default — EditMode suites in Unity, E2E in the browser, regression packs on platforms. Work is done when the suite is green twice in a row, not when it looks done.',
  },
  {
    id: 'HW',
    title: 'Verify on real hardware',
    body: 'A feature verified on a physical headset, tablet or deployed portal is worth ten verified on a dev machine. I close the loop on the device the user actually holds.',
  },
  {
    id: 'AUTO',
    title: 'Automate the meta-work',
    body: 'Weekly reports, cost workbooks, pitch decks, WBS documents — all generated by tooling I built once. Human hours go to decisions, not formatting.',
  },
  {
    id: 'GATE',
    title: 'Autonomy with human gates',
    body: 'I run fleets of AI agents, but every merge crosses a human approval gate with a tamper-proof audit trail. Trust the machine to work; verify before it lands.',
  },
  {
    id: 'SHIP',
    title: 'Velocity is a habit',
    body: 'Nine feature updates in a day. Three phases of a platform rebuild in a weekend. Zero to client-ready in three weeks. Sustained, not heroic — the system makes the pace.',
  },
]

export const projects = [
  {
    tag: 'AI-SDLC',
    accent: 'amber',
    name: 'FORGE — AI Software Delivery Platform',
    period: '2026',
    role: 'Architect & sole builder',
    description:
      'An orchestration platform that drives AI coding agents through a full spec → plan → implement → review → QA pipeline with human approval gates. Fresh repository to a self-running, self-validating system in 18 days.',
    highlights: [
      'Dependency-wave scheduler running up to 8 Claude agents in isolated git worktrees',
      'Automated browser testing verifies every acceptance criterion — it caught a real data-loss defect, and the system fixed itself',
      'Code-knowledge-graph layer so agents consult a graph instead of re-reading files',
      'Local-model routing (Ollama-class) for on-premise deployment; 850 tests green, twice in a row',
    ],
    stack: ['TypeScript', 'Node.js', 'Claude Agents', 'SSE', 'Knowledge Graphs', 'Ollama'],
  },
  {
    tag: 'XR · QA',
    accent: 'cyan',
    name: 'Qualia — AR Quality Inspection',
    period: '2026',
    role: 'Product engineer, zero → client-ready in 3 weeks',
    description:
      'Mixed-reality inspection for manufacturing lines: an in-headset HUD walks operators through dynamic checklists, with a management portal for evidence, analytics and rework traceability.',
    highlights: [
      'Unity + MRTK3 headset build and ARCore tablet port at full feature parity — verified on physical hardware',
      '64/64 EditMode + 7/7 Play-mode E2E tests; TDD from the first commit',
      'Failure → rework → re-inspection workflow with first-pass-yield and scrap-rate analytics',
      'Nine feature updates shipped in a single day on client feedback',
    ],
    stack: ['Unity', 'MRTK3', 'ARCore', 'C#', 'React', 'Express', 'SQLite'],
  },
  {
    tag: 'RAG · DATA',
    accent: 'cyan',
    name: 'Flight Data Insights Platform',
    period: '2025–26',
    role: 'Platform engineer',
    description:
      'A telemetry-analysis portal for flight-test data: RAG-powered querying over raw .dat telemetry, natural-language-to-SQL over live databases, and video evidence pipelines — deployed fully air-gapped.',
    highlights: [
      'NL→SQL (Vanna 2.0) verified live across 13 datasets on the deployed portal',
      'Telemetry ingestion profiling 63-column .dat files with and without parameter headers',
      'MPEG-2 and audio-only video ingest with MP4 playback proxies',
      'Complete offline delivery: Docker images, self-contained installers, air-gap patch bundles',
    ],
    stack: ['Python', 'RAGFlow', 'Vanna 2.0', 'Ollama', 'React', 'Docker', 'MSSQL'],
  },
  {
    tag: 'DEFENSE · SIM',
    accent: 'amber',
    name: 'XR Fighter-Jet Simulator',
    period: '2019–21',
    role: 'Team lead',
    description:
      'Indigenous VR fighter-jet simulator built for a national aeronautics agency: full cockpit interaction, HUD symbology, environment simulation and hand tracking.',
    highlights: [
      'Custom world-space-UV shaders for HUD simulation; physics-joint cockpit switches',
      'Editor scripting auto-rigged hundreds of cockpit controls from engineering spreadsheets',
      'Leap Motion hand-tracked interaction and 6-DOF Quest visualization',
      'Symbology drawing scheduled across multiple cockpit display surfaces',
    ],
    stack: ['Unity', 'C#', 'HLSL', 'Leap Motion', 'Varjo', 'Oculus'],
  },
  {
    tag: 'AVIONICS',
    accent: 'amber',
    name: 'Cockpit Display System (ARINC 661)',
    period: '2021–23',
    role: 'Team lead',
    description:
      'Certified-standard cockpit display software for indigenous fighter programs — low-latency rendering of SVG-based display pages in C and OpenGL.',
    highlights: [
      'ARINC 661-compliant multi-partition dynamic displays with modular updates',
      'Shader-based rendering for real-time graphical elements',
      'Epiphan video capture integration with real-time cropping and UDP streaming via OpenCV',
      'Ada ↔ C++ integration over DLLs and network protocols for airworthy test units',
    ],
    stack: ['C', 'C++', 'OpenGL', 'Ada', 'OpenCV', 'Python'],
  },
  {
    tag: 'DATA · OPS',
    accent: 'cyan',
    name: 'Supplier Intelligence Platform',
    period: '2025–26',
    role: 'Engineer & proposal architect',
    description:
      'A supplier-data aggregation platform with scraping architecture spanning 50+ sources, plus the full commercial package — WBS, staffing plan and costed SOW for a six-month, six-person engagement.',
    highlights: [
      'App-level auth hardening and maintenance-mode infrastructure',
      'Scraping matrix across suppliers and aggregators',
      '5,692-hour costed delivery plan with market-rate modeling',
    ],
    stack: ['React', 'Vite', 'Node.js', 'Scraping', 'xlsx tooling'],
  },
  {
    tag: 'ERGONOMICS',
    accent: 'cyan',
    name: 'Real-Time Pilot Ergonomics',
    period: '2024–25',
    role: 'Lead engineer',
    description:
      'Motion-capture-driven ergonomic analysis of pilots under high-load maneuvering — bone-data extraction, stress metrics, session playback and automated PDF reporting.',
    highlights: [
      'Xsens Movella motion-capture suit integration in Unity',
      'Timestamped posture logging with CSV/JSON export for MATLAB analysis',
      'Auto-generated ergonomic score reports',
    ],
    stack: ['Unity', 'C#', 'Xsens', 'Data pipelines'],
  },
  {
    tag: 'SECURITY',
    accent: 'amber',
    name: 'Air-Gap Data Exchange PoC',
    period: '2026',
    role: 'Built end-to-end in one day',
    description:
      'A complete architecture for moving reviewed data between an offline system and a common server — packaging, auth envelopes, and field-level diff review on both ends — with a working sample application and full documentation.',
    highlights: [
      'ARINC-style change-set packaging with authentication envelopes',
      'File-driven generic UI renderer with editable working copies',
      'Architecture deck, file-format spec and demo script shipped same day',
    ],
    stack: ['TypeScript', 'Vite', 'Custom file formats'],
  },
]

// Personal experiments and open tooling — the after-hours hangar.
export const lab = [
  {
    name: 'Codanium',
    desc: 'Full-service AI software delivery platform — 20+ specialized agents run the whole SDLC behind a PM gatekeeper, with a Tauri desktop IDE companion.',
    stack: 'Next.js 16 · Prisma · Tauri v2 · BullMQ',
  },
  {
    name: 'Plethora',
    desc: 'ADHD-aware daily companion — a proactive coaching agent that keeps every task primed with reward, reason and gentle consequences.',
    stack: 'Next.js 15 · Neon Postgres · LLM tool-calling',
  },
  {
    name: 'Hermes Workspace',
    desc: 'Web command center for the open-source hermes-agent: chat, memory browser, skills marketplace, and a persistent multi-agent swarm mode.',
    stack: 'Node 22 · Docker · tmux swarms',
  },
  {
    name: 'Free-CC',
    desc: 'A protocol proxy that routes Claude Code and Codex traffic to any of 24 LLM backends with streaming, tool-use and per-model routing.',
    stack: 'Python 3.14 · strict CI · semver discipline',
  },
]

export const systems = [
  {
    code: 'SYS-01',
    name: 'AI & Agents',
    items: ['Claude / Claude Code orchestration', 'Multi-agent pipelines & MCP', 'RAG — RAGFlow, Chroma', 'NL→SQL — Vanna 2.0', 'Local LLMs — Ollama', 'Code knowledge graphs'],
  },
  {
    code: 'SYS-02',
    name: 'XR & Simulation',
    items: ['Unity 3D · C#', 'MRTK3 · ARCore · ARFoundation', 'OpenVR · SteamVR · Oculus', 'Varjo XR-3/4 · Quest · Vive', 'Leap Motion · Xsens · SenseGlove', 'FlightGear · Unreal'],
  },
  {
    code: 'SYS-03',
    name: 'Real-Time & Avionics',
    items: ['C · C++ · OpenGL', 'ARINC 661 displays', 'Ada embedded integration', 'Qt · ROS2 · NAV2', 'GLSL / HLSL shaders', 'OpenCV · UDP video streaming'],
  },
  {
    code: 'SYS-04',
    name: 'Web & Platform',
    items: ['TypeScript · React · Vite', 'Node.js · Express · SSE', 'SQLite · MySQL · MSSQL', 'Tailwind · design systems', 'Auth — scrypt, HMAC, RBAC'],
  },
  {
    code: 'SYS-05',
    name: 'Ops & Delivery',
    items: ['Docker · nginx · WSL', 'Air-gapped Linux deployment', 'Git worktree orchestration', 'TDD · browser automation', 'WBS / SOW / costing tooling'],
  },
]
